# Generated by Django 4.0.1 on 2022-01-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=70, verbose_name='Назва машини')),
                ('describe', models.TextField(max_length=300, verbose_name='Опис автомобіля')),
                ('img', models.ImageField(upload_to='media/cars')),
                ('user_id', models.CharField(max_length=10, verbose_name='ID користувача')),
                ('year', models.CharField(max_length=4, verbose_name='Рік випуску автомобіля')),
                ('price', models.CharField(max_length=6, verbose_name='Ціна автомобіля')),
                ('city', models.CharField(max_length=15, verbose_name='Місто продажу')),
                ('mileage', models.CharField(max_length=7, verbose_name='Пробіг автомобіля')),
                ('volume', models.CharField(max_length=30, verbose_name="Об'єм двигуна і тип палива")),
                ('drive', models.CharField(max_length=10, verbose_name='Привід автомобіля')),
                ('color', models.CharField(max_length=15, verbose_name='Колір автомобіля')),
                ('transmission', models.CharField(max_length=15, verbose_name='Тип трансмісії')),
            ],
        ),
    ]
