# Generated by Django 4.0.1 on 2022-01-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_newad_number_of_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newad',
            name='describe',
            field=models.TextField(max_length=800, verbose_name='Опис автомобіля'),
        ),
    ]
