# Generated by Django 4.0.1 on 2022-04-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_newad_describe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newad',
            name='user_id',
            field=models.CharField(blank=True, max_length=10, verbose_name='ID користувача'),
        ),
    ]
