# Generated by Django 4.0.1 on 2022-04-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_newad_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='newad',
            name='user_name',
            field=models.CharField(blank=True, max_length=10, verbose_name='Імя користувача'),
        ),
    ]
