# Generated by Django 4.0.1 on 2022-04-09 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_newad_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='newad',
            name='car_model',
            field=models.CharField(blank=True, max_length=35, verbose_name='Модель машини'),
        ),
    ]
